logging:
  level.org.springframework: INFO
spring:
  datasource:
    url: jdbc:hsqlb:mem:dataSource
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/formacionATSistemas
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect